name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Guard against legacy imports
        run: |
          if git grep -n "kivymd\\.uix\\.iconbutton" -- . ; then
            echo "Forbidden import path detected"; exit 1; fi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

  import-test:
    env:
      KIVY_WINDOW: mock
      KIVY_TEXT: mock
      KIVY_GRAPHICS: mock
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Kivy and KivyMD
        run: |
          python -m pip install --upgrade pip
          pip install --extra-index-url https://kivy.org/downloads/simple/ -r requirements.txt
      - name: Sanity import test
        run: python -c "from kivymd.uix.button import MDIconButton"
      - name: Full import sanity
        run: python -c "import kivy, kivymd; from kivymd.uix.button import MDIconButton"
      - name: KV smoke (headless)
        run: |
          python - <<'PY'
          from pathlib import Path

          from kivy.lang import Builder
          from kivy.resources import resource_add_path
          from kivymd.uix.button import MDIconButton

          gui_root = Path('resource/theme/gui')
          resource_add_path(str(gui_root))
          Builder.load_file(str(gui_root / 'app.kv'))
          print('kv ok')
          PY
