name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

  import-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Kivy and KivyMD
        run: |
          python -m pip install --upgrade pip
          pip install --extra-index-url https://kivy.org/downloads/simple/ -r requirements.txt
      - name: Sanity import test
        run: python -c "from kivymd.uix.button import MDIconButton"
